name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Deploy to remote server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USERNAME }}
                  password: ${{ secrets.REMOTE_PASSWORD }}
                  port: ${{ secrets.REMOTE_PORT }}
                  script: |
                      cd ${{ secrets.REMOTE_WORKDIR }}
                      git reset --hard origin/main
                      git pull
                      echo "${{ secrets.DEPLOY_ENV_FILE }}" > .env
                      echo "${{ secrets.DEPLOY_ENV_PROD_FILE }}" > .env.prod
                      npm install
                      npm run docker:build
